
all:
#	g++ main.cpp TcpListener.cpp WebServer.cpp -o main -lssl -lcrypto -Wall -Werror 
#	g++ main.cpp TcpListener.cpp WebServer.cpp -o main -lssl -lcrypto -Wall
	g++ main.cpp TcpListener.cpp JSONParser.cpp TelegramBot.cpp HTTPParser.cpp WebServer.cpp -o main -lssl -lcrypto -Wall 
